apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomizatio

namespace: boutique

resources:
#  - trivy_operator.yaml
  - namespace.yaml
  - https://raw.githubusercontent.com/GoogleCloudPlatform/microservices-demo/main/kubernetes-manifests/frontend.yaml
