apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - trivy_operator.yaml
  - boutique/
#  - https://raw.githubusercontent.com/GoogleCloudPlatform/microservices-demo/main/kubernetes-manifests/frontend.yaml
